SET vArchiveName = L1_MYSQL_dimproductcategory;

[$(vArchiveName)]:
SELECT ProductCategoryKey,
	ProductCategoryLabel,
	ProductCategoryName,
	ProductCategoryDescription,
	ETLLoadID,
	LoadDate,
	UpdateDate
FROM spanish.dimproductcategory;

Store $(vArchiveName) into [$(vR_QvdExt)$(vArchiveName).qvd]  (qvd);
Drop table $(vArchiveName);

//---------------------------------------------------------------------------------